### ISSUE TITLE
Issue with React.Portal ?

### ISSUE THREAD

**Issue by WaSa42** [danawoodman/react-fontawesome#64] opened 2018-01-07 17:58 UTC
I'm trying to make a sign in button like in this code:
``` javascript
renderSignInButton() {
        const { credentials, dispatch, profile, t } = this.props;
        const { token } = credentials;

        if (token) {
            if (profile.isFetching) {
                return (
                    <button type="button" disabled>
                        <FontAwesomeIcon icon={faSpinner} spin />
                        {t('form:signIn.state.isFetching')}
                    </button>
                );
            }

            return (
                <button type="button" onClick={() => dispatch(signOut())}>
                    <FontAwesomeIcon icon={faSignOutAlt} />
                    {t('form:signIn.button.signOut')}
                </button>
            );
        }

        return (
            <button type="button">
                <FontAwesomeIcon icon={faSignInAlt} />
                {t('form:signIn.button.default')}
            </button>
        );
    }
```

But when the props are updated and the button is rerendered with a different icon, the code differs from the page:

![image](https://user-images.githubusercontent.com/6498751/34652205-908ba8e6-f3db-11e7-988a-a6f71740d37f.png)

![image](https://user-images.githubusercontent.com/6498751/34652217-a20f12e2-f3db-11e7-82f3-88e2403925a5.png)

You see, the React Dev Tools is showing `faSignOutAlt` and `faSpinner`  icon is displayed on the page.

I'm using React.Portal feature to render this button.
Don't know what to do.

**Comment by danawoodman** [comment] 2018-01-07 19:11
Unfortunately this doesn’t have to do with react-fontawesome since it is just a simple component.

It looks like you’re passing an object to `icon` which is not how you use this component. Do you have a wrapper around react-fontawesome? If so, what does that look like? Can you send a minimal test example that reproduces this behavior?

Closing since this isn’t a react-fontawesome issue afaik.

**Closed by danawoodman** 2018-01-07 19:11 UTC

**Comment by WaSa42** [comment] 2018-01-07 22:43
I was wondering why you said that I was passing an object to icon.
It's because I confounded you repo with the [FontAwesome 5 repo for React](https://github.com/FortAwesome/react-fontawesome).
Conclusion: I'm a dumb person and sorry for the trouble. x)

**Comment by danawoodman** [comment] 2018-01-09 18:15
Haha, that would do it 😜 glad you figured it out 👌
