### ISSUE TITLE
1.5.0 Error Rendering

### ISSUE THREAD

**Issue by jatsrt** [danawoodman/react-fontawesome#33] opened 2016-12-08 15:17 UTC
I haven't dug into the details, but on a basic:

```
ReactDOM.render(
    <FontAwesome name="twitter" />,
    document.getElementById("root")
);
```

I am getting: 

> VM2236 react.js:3639Warning: React.createElement: type should not be null, undefined, boolean, or number. It should be a string (for DOM elements) or a ReactClass (for composite components).

**Comment by danawoodman** [comment] 2016-12-12 20:13
@jatsrt that's strange, let me look into it

**Comment by danawoodman** [comment] 2016-12-12 20:48
@jatsrt I'm not able to reproduce this. I've created [`examples/`](https://github.com/danawoodman/react-fontawesome/tree/master/examples) directory to troubleshoot the issue, can you check the webpack config and `index.js` file to see if you're using everything right?

**Comment by danawoodman** [comment] 2016-12-14 20:54
Closing now, please re-open if you believe it is indeed a react-fontawesome issue!

**Closed by danawoodman** 2016-12-14 20:54 UTC
